In [84]:
import pandas as pd
import numpy as np
from scipy.signal import find_peaks

In [9]:
df = pd.read_csv('Read the sumed runoff file')
print(df.head())

         Past      Future  Timesteps  Past_Chili  Future_Chili  Past_Colca  \
0  166.998400  573.919205        0.0   13.824327     63.661362  153.174072   
1  157.818900  698.844458        1.0   13.897498     28.189245  143.921402   
2  159.517353  359.465429        2.0   13.981678     11.125189  145.535675   
3  162.383473  300.180075        3.0   14.064092      7.718191  148.319382   
4  174.392297  300.968145        4.0   14.157418      7.649389  160.234879   

   Future_Colca Unnamed: 7  
0    510.257843        NaN  
1    670.655212        NaN  
2    348.340240        NaN  
3    292.461883        NaN  
4    293.318756        NaN  


In [12]:
t_Past=df['Past'].to_numpy()
t_Future=df['Future'].to_numpy()
chili_p=df['Past_Chili'].to_numpy()
chili_f=df['Future_Chili'].to_numpy()
colca_p=df['Past_Colca'].to_numpy()
colca_f=df['Future_Colca'].to_numpy()

In [271]:
# Find indices of local maxima (ups)
ups, _ = find_peaks(t_Past,prominence=1000)
print(ups)
# fine the first index that's the start of the falling limb
start = []
for up in ups:
    following_start = np.where(t_Past[up:] < 550)[0]
    if len(following_start) > 0:
        start.append(up + following_start[0])  # Add the actual index
print(start)
# Find the first index below the threshold after each up
downs = []
for s in start:
    # Look for the first index where the data drops below the threshold
    following_down = np.where(t_Past[s:] < 10)[0]
    if len(following_down) > 0:
        downs.append(s + following_down[0])  # Add the actual index
print(downs)
downs = np.array(downs)
start=np.array(start)
# Compute index differences
index_differences = downs -start 
index_differences = index_differences[index_differences>=50]
print(index_differences)

[  367  3343  6502  9334 12087]
[730, 3467, 6696, 9521, 12432]
[1984, 4599, 7527, 10239, 13095]
[1254 1132  831  718  663]


In [273]:
# Find indices of local maxima (ups)
ups, _ = find_peaks(t_Future,prominence=1000)
# fine the first index that's the start of the falling limb
start = []
for up in ups:
    following_start = np.where(t_Future[up:] < 550)[0]
    if len(following_start) > 0:
        start.append(up + following_start[0])  # Add the actual index

# Find the first index below the threshold after each up
downs = []
for s in start:
    # Look for the first index where the data drops below the threshold
    following_down = np.where(t_Future[s:] < 10)[0]
    if len(following_down) > 0:
        downs.append(s + following_down[0])  # Add the actual index

downs = np.array(downs)
start=np.array(start)
# Compute index differences
index_differences_f = downs-start
index_differences_f = index_differences_f[index_differences_f>=50]
print(index_differences_f)

[1145  681  425  687  689  441 1028  775  565  342  342  342]


In [275]:
d=(np.mean(index_differences)-np.mean(index_differences_f))*3/24
print(d)

37.22083333333333


In [335]:
# find the starting time change
# Find indices of local maxima (ups)
ups, _ = find_peaks(chili_p,prominence=450)

# find the close to last index that's the end of the raising limb
start = []
for up in ups:
    following_start = np.where(chili_p[:up] < 150)[0]
    if len(following_start) > 0:
        start.append(up + following_start[0])  # Add the actual index
print(start)

# Find the first index below the threshold after each up
downs = []
for s in start:
    for i in range(s-1,-1,-1):
        if chili_p[i] < 3:
            downs.append(i)
            break
        elif i==0:
            downs.append(0)
            break
            
print(downs)
downs = np.array(downs)
start=np.array(start)
# Compute index differences
index_differences = start - downs
index_differences = index_differences[index_differences>=520]
print(index_differences)

[367, 519, 3335, 3344, 6502, 9334, 12056]
[0, 0, 2418, 2418, 5882, 8363, 11675]
[917 926 620 971]


In [345]:
# find the starting time change
# Find indices of local maxima (ups)
ups, _ = find_peaks(chili_f,prominence=550)

# find the close to last index that's the end of the raising limb
start = []
for up in ups:
    following_start = np.where(chili_f[:up] < 150)[0]
    if len(following_start) > 0:
        start.append(up + following_start[0])  # Add the actual index
print(start)

# Find the first index below the threshold after each up
downs = []
for s in start:
    for i in range(s-1,-1,-1):
        if chili_f[i] < 3:
            downs.append(i)
            break
        elif i==0:
            downs.append(0)
            break
            
print(downs)
downs = np.array(downs)
start=np.array(start)
# Compute index differences
index_differences_f = start - downs
index_differences_f = index_differences_f[index_differences_f>=450]
print(index_differences_f)

[767, 6407, 9215, 9399, 12079, 12263]
[0, 6059, 8833, 8833, 11813, 11813]
[767 566 450]


In [347]:
d=(np.mean(index_differences)-np.mean(index_differences_f))*3/24
print(d)

33.02083333333333
